package utils

import "machine/usb/hid/keyboard"

func KeycodeFromString(s string) keyboard.Keycode {
	switch s {
	case "KeyModifierCtrl":
		return keyboard.KeyModifierCtrl
	case "KeyModifierShift":
		return keyboard.KeyModifierShift
	case "KeyModifierAlt":
		return keyboard.KeyModifierAlt
	case "KeyModifierGUI":
		return keyboard.KeyModifierGUI
	case "KeyModifierLeftCtrl":
		return keyboard.KeyModifierLeftCtrl
	case "KeyModifierLeftShift":
		return keyboard.KeyModifierLeftShift
	case "KeyModifierLeftAlt":
		return keyboard.KeyModifierLeftAlt
	case "KeyModifierLeftGUI":
		return keyboard.KeyModifierLeftGUI
	case "KeyModifierRightCtrl":
		return keyboard.KeyModifierRightCtrl
	case "KeyModifierRightShift":
		return keyboard.KeyModifierRightShift
	case "KeyModifierRightAlt":
		return keyboard.KeyModifierRightAlt
	case "KeyModifierRightGUI":
		return keyboard.KeyModifierRightGUI

	// KeySystemXXX is not supported now
	case "KeySystemPowerDown":
		return keyboard.KeySystemPowerDown
	case "KeySystemSleep":
		return keyboard.KeySystemSleep
	case "KeySystemWakeUp":
		return keyboard.KeySystemWakeUp

	case "KeyMediaPlay":
		return keyboard.KeyMediaPlay
	case "KeyMediaPause":
		return keyboard.KeyMediaPause
	case "KeyMediaRecord":
		return keyboard.KeyMediaRecord
	case "KeyMediaFastForward":
		return keyboard.KeyMediaFastForward
	case "KeyMediaRewind":
		return keyboard.KeyMediaRewind
	case "KeyMediaNextTrack":
		return keyboard.KeyMediaNextTrack
	case "KeyMediaPrevTrack":
		return keyboard.KeyMediaPrevTrack
	case "KeyMediaStop":
		return keyboard.KeyMediaStop
	case "KeyMediaEject":
		return keyboard.KeyMediaEject
	case "KeyMediaRandomPlay":
		return keyboard.KeyMediaRandomPlay
	case "KeyMediaPlayPause":
		return keyboard.KeyMediaPlayPause
	case "KeyMediaPlaySkip":
		return keyboard.KeyMediaPlaySkip
	case "KeyMediaMute":
		return keyboard.KeyMediaMute
	case "KeyMediaVolumeInc":
		return keyboard.KeyMediaVolumeInc
	case "KeyMediaVolumeDec":
		return keyboard.KeyMediaVolumeDec

	case "KeyA":
		return keyboard.KeyA
	case "KeyB":
		return keyboard.KeyB
	case "KeyC":
		return keyboard.KeyC
	case "KeyD":
		return keyboard.KeyD
	case "KeyE":
		return keyboard.KeyE
	case "KeyF":
		return keyboard.KeyF
	case "KeyG":
		return keyboard.KeyG
	case "KeyH":
		return keyboard.KeyH
	case "KeyI":
		return keyboard.KeyI
	case "KeyJ":
		return keyboard.KeyJ
	case "KeyK":
		return keyboard.KeyK
	case "KeyL":
		return keyboard.KeyL
	case "KeyM":
		return keyboard.KeyM
	case "KeyN":
		return keyboard.KeyN
	case "KeyO":
		return keyboard.KeyO
	case "KeyP":
		return keyboard.KeyP
	case "KeyQ":
		return keyboard.KeyQ
	case "KeyR":
		return keyboard.KeyR
	case "KeyS":
		return keyboard.KeyS
	case "KeyT":
		return keyboard.KeyT
	case "KeyU":
		return keyboard.KeyU
	case "KeyV":
		return keyboard.KeyV
	case "KeyW":
		return keyboard.KeyW
	case "KeyX":
		return keyboard.KeyX
	case "KeyY":
		return keyboard.KeyY
	case "KeyZ":
		return keyboard.KeyZ
	case "Key1":
		return keyboard.Key1
	case "Key2":
		return keyboard.Key2
	case "Key3":
		return keyboard.Key3
	case "Key4":
		return keyboard.Key4
	case "Key5":
		return keyboard.Key5
	case "Key6":
		return keyboard.Key6
	case "Key7":
		return keyboard.Key7
	case "Key8":
		return keyboard.Key8
	case "Key9":
		return keyboard.Key9
	case "Key0":
		return keyboard.Key0
	case "KeyEnter":
		return keyboard.KeyEnter
	case "KeyEsc":
		return keyboard.KeyEsc
	case "KeyBackspace":
		return keyboard.KeyBackspace
	case "KeyTab":
		return keyboard.KeyTab
	case "KeySpace":
		return keyboard.KeySpace
	case "KeyMinus":
		return keyboard.KeyMinus
	case "KeyEqual":
		return keyboard.KeyEqual
	case "KeyLeftBrace":
		return keyboard.KeyLeftBrace
	case "KeyRightBrace":
		return keyboard.KeyRightBrace
	case "KeyBackslash":
		return keyboard.KeyBackslash
	case "KeyNonUsNum":
		return keyboard.KeyNonUsNum
	case "KeySemicolon":
		return keyboard.KeySemicolon
	case "KeyQuote":
		return keyboard.KeyQuote
	case "KeyTilde":
		return keyboard.KeyTilde
	case "KeyComma":
		return keyboard.KeyComma
	case "KeyPeriod":
		return keyboard.KeyPeriod
	case "KeySlash":
		return keyboard.KeySlash
	case "KeyCapsLock":
		return keyboard.KeyCapsLock
	case "KeyF1":
		return keyboard.KeyF1
	case "KeyF2":
		return keyboard.KeyF2
	case "KeyF3":
		return keyboard.KeyF3
	case "KeyF4":
		return keyboard.KeyF4
	case "KeyF5":
		return keyboard.KeyF5
	case "KeyF6":
		return keyboard.KeyF6
	case "KeyF7":
		return keyboard.KeyF7
	case "KeyF8":
		return keyboard.KeyF8
	case "KeyF9":
		return keyboard.KeyF9
	case "KeyF10":
		return keyboard.KeyF10
	case "KeyF11":
		return keyboard.KeyF11
	case "KeyF12":
		return keyboard.KeyF12
	case "KeyPrintscreen":
		return keyboard.KeyPrintscreen
	case "KeyScrollLock":
		return keyboard.KeyScrollLock
	case "KeyPause":
		return keyboard.KeyPause
	case "KeyInsert":
		return keyboard.KeyInsert
	case "KeyHome":
		return keyboard.KeyHome
	case "KeyPageUp":
		return keyboard.KeyPageUp
	case "KeyDelete":
		return keyboard.KeyDelete
	case "KeyEnd":
		return keyboard.KeyEnd
	case "KeyPageDown":
		return keyboard.KeyPageDown
	case "KeyRight":
		return keyboard.KeyRight
	case "KeyLeft":
		return keyboard.KeyLeft
	case "KeyDown":
		return keyboard.KeyDown
	case "KeyUp":
		return keyboard.KeyUp
	case "KeyNumLock":
		return keyboard.KeyNumLock
	case "KeypadSlash":
		return keyboard.KeypadSlash
	case "KeypadAsterisk":
		return keyboard.KeypadAsterisk
	case "KeypadMinus":
		return keyboard.KeypadMinus
	case "KeypadPlus":
		return keyboard.KeypadPlus
	case "KeypadEnter":
		return keyboard.KeypadEnter
	case "Keypad1":
		return keyboard.Keypad1
	case "Keypad2":
		return keyboard.Keypad2
	case "Keypad3":
		return keyboard.Keypad3
	case "Keypad4":
		return keyboard.Keypad4
	case "Keypad5":
		return keyboard.Keypad5
	case "Keypad6":
		return keyboard.Keypad6
	case "Keypad7":
		return keyboard.Keypad7
	case "Keypad8":
		return keyboard.Keypad8
	case "Keypad9":
		return keyboard.Keypad9
	case "Keypad0":
		return keyboard.Keypad0
	case "KeypadPeriod":
		return keyboard.KeypadPeriod
	case "KeyNonUSBS":
		return keyboard.KeyNonUSBS
	case "KeyMenu":
		return keyboard.KeyMenu
	case "KeyF13":
		return keyboard.KeyF13
	case "KeyF14":
		return keyboard.KeyF14
	case "KeyF15":
		return keyboard.KeyF15
	case "KeyF16":
		return keyboard.KeyF16
	case "KeyF17":
		return keyboard.KeyF17
	case "KeyF18":
		return keyboard.KeyF18
	case "KeyF19":
		return keyboard.KeyF19
	case "KeyF20":
		return keyboard.KeyF20
	case "KeyF21":
		return keyboard.KeyF21
	case "KeyF22":
		return keyboard.KeyF22
	case "KeyF23":
		return keyboard.KeyF23
	case "KeyF24":
		return keyboard.KeyF24

	case "KeyUpArrow":
		return keyboard.KeyUpArrow
	case "KeyDownArrow":
		return keyboard.KeyDownArrow
	case "KeyLeftArrow":
		return keyboard.KeyLeftArrow
	case "KeyRightArrow":
		return keyboard.KeyRightArrow
	case "KeyReturn":
		return keyboard.KeyReturn
	case "KeyLeftCtrl":
		return keyboard.KeyLeftCtrl
	case "KeyLeftShift":
		return keyboard.KeyLeftShift
	case "KeyLeftAlt":
		return keyboard.KeyLeftAlt
	case "KeyLeftGUI":
		return keyboard.KeyLeftGUI
	case "KeyRightCtrl":
		return keyboard.KeyRightCtrl
	case "KeyRightShift":
		return keyboard.KeyRightShift
	case "KeyRightAlt":
		return keyboard.KeyRightAlt
	case "KeyRightGUI":
		return keyboard.KeyRightGUI
	}
	return 0
}

func KeycodeToString(kc keyboard.Keycode) string {
	switch kc {
	case keyboard.KeyModifierCtrl:
		return "KeyModifierCtrl"
	case keyboard.KeyModifierShift:
		return "KeyModifierShift"
	case keyboard.KeyModifierAlt:
		return "KeyModifierAlt"
	case keyboard.KeyModifierGUI:
		return "KeyModifierGUI"
	case keyboard.KeyModifierRightCtrl:
		return "KeyModifierRightCtrl"
	case keyboard.KeyModifierRightShift:
		return "KeyModifierRightShift"
	case keyboard.KeyModifierRightAlt:
		return "KeyModifierRightAlt"
	case keyboard.KeyModifierRightGUI:
		return "KeyModifierRightGUI"

	// KeySystemXXX is not supported now
	case keyboard.KeySystemPowerDown:
		return "KeySystemPowerDown"
	case keyboard.KeySystemSleep:
		return "KeySystemSleep"
	case keyboard.KeySystemWakeUp:
		return "KeySystemWakeUp"

	case keyboard.KeyMediaPlay:
		return "KeyMediaPlay"
	case keyboard.KeyMediaPause:
		return "KeyMediaPause"
	case keyboard.KeyMediaRecord:
		return "KeyMediaRecord"
	case keyboard.KeyMediaFastForward:
		return "KeyMediaFastForward"
	case keyboard.KeyMediaRewind:
		return "KeyMediaRewind"
	case keyboard.KeyMediaNextTrack:
		return "KeyMediaNextTrack"
	case keyboard.KeyMediaPrevTrack:
		return "KeyMediaPrevTrack"
	case keyboard.KeyMediaStop:
		return "KeyMediaStop"
	case keyboard.KeyMediaEject:
		return "KeyMediaEject"
	case keyboard.KeyMediaRandomPlay:
		return "KeyMediaRandomPlay"
	case keyboard.KeyMediaPlayPause:
		return "KeyMediaPlayPause"
	case keyboard.KeyMediaPlaySkip:
		return "KeyMediaPlaySkip"
	case keyboard.KeyMediaMute:
		return "KeyMediaMute"
	case keyboard.KeyMediaVolumeInc:
		return "KeyMediaVolumeInc"
	case keyboard.KeyMediaVolumeDec:
		return "KeyMediaVolumeDec"

	case keyboard.KeyA:
		return "KeyA"
	case keyboard.KeyB:
		return "KeyB"
	case keyboard.KeyC:
		return "KeyC"
	case keyboard.KeyD:
		return "KeyD"
	case keyboard.KeyE:
		return "KeyE"
	case keyboard.KeyF:
		return "KeyF"
	case keyboard.KeyG:
		return "KeyG"
	case keyboard.KeyH:
		return "KeyH"
	case keyboard.KeyI:
		return "KeyI"
	case keyboard.KeyJ:
		return "KeyJ"
	case keyboard.KeyK:
		return "KeyK"
	case keyboard.KeyL:
		return "KeyL"
	case keyboard.KeyM:
		return "KeyM"
	case keyboard.KeyN:
		return "KeyN"
	case keyboard.KeyO:
		return "KeyO"
	case keyboard.KeyP:
		return "KeyP"
	case keyboard.KeyQ:
		return "KeyQ"
	case keyboard.KeyR:
		return "KeyR"
	case keyboard.KeyS:
		return "KeyS"
	case keyboard.KeyT:
		return "KeyT"
	case keyboard.KeyU:
		return "KeyU"
	case keyboard.KeyV:
		return "KeyV"
	case keyboard.KeyW:
		return "KeyW"
	case keyboard.KeyX:
		return "KeyX"
	case keyboard.KeyY:
		return "KeyY"
	case keyboard.KeyZ:
		return "KeyZ"
	case keyboard.Key1:
		return "Key1"
	case keyboard.Key2:
		return "Key2"
	case keyboard.Key3:
		return "Key3"
	case keyboard.Key4:
		return "Key4"
	case keyboard.Key5:
		return "Key5"
	case keyboard.Key6:
		return "Key6"
	case keyboard.Key7:
		return "Key7"
	case keyboard.Key8:
		return "Key8"
	case keyboard.Key9:
		return "Key9"
	case keyboard.Key0:
		return "Key0"
	case keyboard.KeyEnter:
		return "KeyEnter"
	case keyboard.KeyEsc:
		return "KeyEsc"
	case keyboard.KeyBackspace:
		return "KeyBackspace"
	case keyboard.KeyTab:
		return "KeyTab"
	case keyboard.KeySpace:
		return "KeySpace"
	case keyboard.KeyMinus:
		return "KeyMinus"
	case keyboard.KeyEqual:
		return "KeyEqual"
	case keyboard.KeyLeftBrace:
		return "KeyLeftBrace"
	case keyboard.KeyRightBrace:
		return "KeyRightBrace"
	case keyboard.KeyBackslash:
		return "KeyBackslash"
	case keyboard.KeyNonUsNum:
		return "KeyNonUsNum"
	case keyboard.KeySemicolon:
		return "KeySemicolon"
	case keyboard.KeyQuote:
		return "KeyQuote"
	case keyboard.KeyTilde:
		return "KeyTilde"
	case keyboard.KeyComma:
		return "KeyComma"
	case keyboard.KeyPeriod:
		return "KeyPeriod"
	case keyboard.KeySlash:
		return "KeySlash"
	case keyboard.KeyCapsLock:
		return "KeyCapsLock"
	case keyboard.KeyF1:
		return "KeyF1"
	case keyboard.KeyF2:
		return "KeyF2"
	case keyboard.KeyF3:
		return "KeyF3"
	case keyboard.KeyF4:
		return "KeyF4"
	case keyboard.KeyF5:
		return "KeyF5"
	case keyboard.KeyF6:
		return "KeyF6"
	case keyboard.KeyF7:
		return "KeyF7"
	case keyboard.KeyF8:
		return "KeyF8"
	case keyboard.KeyF9:
		return "KeyF9"
	case keyboard.KeyF10:
		return "KeyF10"
	case keyboard.KeyF11:
		return "KeyF11"
	case keyboard.KeyF12:
		return "KeyF12"
	case keyboard.KeyPrintscreen:
		return "KeyPrintscreen"
	case keyboard.KeyScrollLock:
		return "KeyScrollLock"
	case keyboard.KeyPause:
		return "KeyPause"
	case keyboard.KeyInsert:
		return "KeyInsert"
	case keyboard.KeyHome:
		return "KeyHome"
	case keyboard.KeyPageUp:
		return "KeyPageUp"
	case keyboard.KeyDelete:
		return "KeyDelete"
	case keyboard.KeyEnd:
		return "KeyEnd"
	case keyboard.KeyPageDown:
		return "KeyPageDown"
	case keyboard.KeyRight:
		return "KeyRight"
	case keyboard.KeyLeft:
		return "KeyLeft"
	case keyboard.KeyDown:
		return "KeyDown"
	case keyboard.KeyUp:
		return "KeyUp"
	case keyboard.KeyNumLock:
		return "KeyNumLock"
	case keyboard.KeypadSlash:
		return "KeypadSlash"
	case keyboard.KeypadAsterisk:
		return "KeypadAsterisk"
	case keyboard.KeypadMinus:
		return "KeypadMinus"
	case keyboard.KeypadPlus:
		return "KeypadPlus"
	case keyboard.KeypadEnter:
		return "KeypadEnter"
	case keyboard.Keypad1:
		return "Keypad1"
	case keyboard.Keypad2:
		return "Keypad2"
	case keyboard.Keypad3:
		return "Keypad3"
	case keyboard.Keypad4:
		return "Keypad4"
	case keyboard.Keypad5:
		return "Keypad5"
	case keyboard.Keypad6:
		return "Keypad6"
	case keyboard.Keypad7:
		return "Keypad7"
	case keyboard.Keypad8:
		return "Keypad8"
	case keyboard.Keypad9:
		return "Keypad9"
	case keyboard.Keypad0:
		return "Keypad0"
	case keyboard.KeypadPeriod:
		return "KeypadPeriod"
	case keyboard.KeyNonUSBS:
		return "KeyNonUSBS"
	case keyboard.KeyMenu:
		return "KeyMenu"
	case keyboard.KeyF13:
		return "KeyF13"
	case keyboard.KeyF14:
		return "KeyF14"
	case keyboard.KeyF15:
		return "KeyF15"
	case keyboard.KeyF16:
		return "KeyF16"
	case keyboard.KeyF17:
		return "KeyF17"
	case keyboard.KeyF18:
		return "KeyF18"
	case keyboard.KeyF19:
		return "KeyF19"
	case keyboard.KeyF20:
		return "KeyF20"
	case keyboard.KeyF21:
		return "KeyF21"
	case keyboard.KeyF22:
		return "KeyF22"
	case keyboard.KeyF23:
		return "KeyF23"
	case keyboard.KeyF24:
		return "KeyF24"
	}
	return ""
}
